### ISSUE TITLE
password error

### ISSUE THREAD

**Issue by zhaoxueye** [hsa00000/Urocissa#13]
**Describe the bug**
password error 

**To Reproduce**
1. set Urocissa/gallery-backend/.env PASSWORD=123456
2. error log
2024-11-29T06:34:28Z WARN Urocissa::router::post::authenticate::_
           Data guard `Json < String >` failed: Parse("123456", Error("invalid type: integer `123456`, expected a string", line: 1, column: 6)).
2024-11-29T06:34:28Z WARN rocket::server::_
           No 422 catcher registered. Using Rocket default.
^C2024-11-29T06:37:06Z WARN rocket::server
3. set PASSWORD=aabbcc
4. error log
024-11-29T06:39:37Z INFO Urocissa::public::config
           config.json not found. Using default configuration.
2024-11-29T06:39:37Z WARN Urocissa::router::fairing
           Unauthorized access attempt via fetch.
2024-11-29T06:39:37Z WARN rocket::server::_
           No 401 catcher registered. Using Rocket default.

**Comment by hsa00000** [comment]
Dear @zhaoxueye,

I've implemented a fix in [commit 2af1f7d](https://github.com/hsa00000/Urocissa/commit/2af1f7d23599c0d06cb25371a6b298155b3b15db) that should resolve the issue you've encountered.

Please follow these steps to update to the latest version:

**Update Instructions**

1. **Pull the Latest Changes from the Repository**
   
   Navigate to the project directory and pull the latest updates:

   ```bash
   git pull
   ```

2. **Rebuild the Frontend**

   Navigate to the gallery-frontend directory:

   ```bash
   cd ./Urocissa/gallery-frontend
   ```

   Build the frontend:

   ```bash
   npm run build
   ```

3. **Rebuild the Backend**

   Navigate to the gallery-backend directory:

   ```bash
   cd ./Urocissa/gallery-backend
   ```

   Build and run the backend using Cargo:

   ```bash
   cargo run --release
   ```

Please let me know if this resolves the issue or if you need any further assistance, and kindly verify if the problem has been fixed.

**Remark**: After updating the password, you must restart the backend.
