### ISSUE TITLE
Reusing password for authentication and JWT EncodingKey

### ISSUE THREAD

**Issue by nils-werner** [hsa00000/Urocissa#2]
In `/src/router/post/authenticate.rs` you're using the config password as a means of authentication

```
if input_password == PRIVATE_CONFIG.password {
    ...
}
```

and later also to sign the JWT

```
let token = encode(
    ...
    &EncodingKey::from_secret(PRIVATE_CONFIG.password.as_ref()),
)
```

This is insecure because it allows any user with the password to create and sign JWTs themselves, granting themselves any permission they like.

You should use two different secrets here. One that the user knows, and one that only the server knows.

**Comment by hsa00000** [comment]
Thank you for your feedback. I’ve updated the implementation to use a separate secret for JWT. This secret key is now randomly generated at the time of app startup. It seems that this is not a common practice, but it should be sufficient given the scale of this application and its security requirements. If you have any further suggestions or concerns, feel free to share.

**Comment by nils-werner** [comment]
I think that should fix the security issue.

But I also think it's a good idea to eventually make this is configurable because you have to use the same JWT secret when mixing multiple services or applications. That way you can i.e. use an authentication app like Keycloak and have it create the JWTs for Urocissa.
