### ISSUE TITLE
Firefox login issue

### ISSUE THREAD

**Issue by Imberflur** [hsa00000/Urocissa#5]
I saw some discussion about login failing on reddit, in particular with firefox.

After testing myself, it looks like when the initial navigation to reach the site was cross-origin, the cookie isn't sent in firefox when using `window.location.reload()` :
https://github.com/hsa00000/Urocissa/blob/404d1094b219547aec0a4aaefadd0152b9dab9e1/gallery-frontend/src/components/LoginPage.vue#L42

This behavior is discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1459321

If I manually navigate to the site root after trying to login, it sends the cookie and loads properly.

It seems like the fix would be to find an alternative to `window.location.reload()` here that counts as a same site request in firefox.

**Comment by hsa00000** [comment]
Thank you for your help. I initially used window.location.reload() as an improper workaround for my incorrect use of Vue Router. Now that I’ve fixed the misuse in a255caaa2c78217983929799acc00885188caf0f, it’s no longer necessary.
