### ISSUE TITLE
Separate Sensitive Settings into `.env` File

### ISSUE THREAD

**Issue by KiringYJ** [hsa00000/Urocissa#7]
**Is your feature request related to a problem? Please describe.**
Currently, sensitive settings like passwords and webhook URLs are stored directly in `config.ts` (frontend) and `config.json` (backend). This approach has the following challenges:
1. **Mixing Sensitive and Non-Sensitive Settings**: Combining these settings makes configuration files harder to manage and increases the risk of accidental exposure.
2. **Manual Editing Requirements**: Users must manually edit these files, which can be error-prone, especially for less experienced users.
3. **Security Risk**: Sensitive data stored directly in source files increases the likelihood of accidental commits to version control.

**Describe the solution you'd like**
To address these issues, I propose separating sensitive settings into a `.env` file:
- **Frontend**:
  - Replace hardcoded sensitive values in `config.ts` with environment variables (e.g., `VITE_API_PASSWORD`).
  - Inject these variables into the build process using tools like `dotenv` or native Vite environment variable support.
- **Backend**:
  - Move sensitive fields (e.g., `password`, `discordHookUrl`) from `config.json` to a `.env` file.
  - Use a Rust library like `dotenv` or `env_logger` to load environment variables at runtime.

**Implementation Steps**:
1. **Modify Configuration Files**:
   - Replace sensitive fields in `config.json` and `config.ts` with references to environment variables.
2. **Add Environment Variable Loader**:
   - For the backend, integrate a library like `dotenv` to load variables from `.env` at runtime.
   - For the frontend, configure Vite to inject environment variables into the build process.
3. **Provide Default `.env` Template**:
   - Include a `.env.example` file in the repository with placeholders for required sensitive settings.
4. **Update Documentation**:
   - Add instructions to create a `.env` file based on `.env.example`.
   - Provide CLI commands or scripts to automate the creation and initialization of the `.env` file.

**Benefits of This Approach**:
1. **Simplified Installation**:
   - A CLI command can be used to auto-generate the `.env` file, reducing manual setup steps.
2. **Enhanced Security**:
   - Keeps sensitive data out of version control by adding `.env` to `.gitignore`.
   - Reduces the likelihood of exposing sensitive information accidentally.
3. **Improved Maintainability**:
   - Clear separation between sensitive and non-sensitive settings makes configuration files easier to manage and understand.
   - Aligns with industry best practices for managing sensitive application settings.

**Describe alternatives you've considered**
1. **Document-Only Changes**:
   - Adding detailed instructions to guide users on editing `config.json` and `config.ts` manually. However, this approach still risks exposing sensitive data and increases the likelihood of user errors.
2. **Encrypting Sensitive Data**:
   - Encrypting sensitive settings in existing files. While this would increase security, it adds unnecessary complexity and requires additional tools or services for encryption and decryption.

**Additional context**
Many modern frameworks and tools use `.env` files to manage sensitive data because they are simple, secure, and compatible with most deployment pipelines. Libraries like `dotenv` (for Rust and Node.js) make it easy to integrate `.env` files with minimal changes to the existing codebase.

This feature would align with Urocissa's goals of being efficient, user-friendly, and scalable while adhering to best practices in application security.

**Comment by hsa00000** [comment]
Thank you for raising this issue. This request has been addressed and resolved in version [0.3.0](https://github.com/hsa00000/Urocissa/releases/tag/0.3.0) of Urocissa. Please refer to the [changelog](https://github.com/hsa00000/Urocissa/releases/tag/0.3.0#breaking-changes) for details on the changes and migration steps.
