### ISSUE TITLE
Will this work on windows machines?

### ISSUE THREAD

**Issue by BBC-Esq** [hsa00000/Urocissa#8]
Will this work on windows?  I've never used Rust before and a lot of repositories seem to only work on linux for some ungodly reason?

**Comment by hsa00000** [comment]
Yes, Urocissa works on Windows as well. The installation steps are quite similar to those for Linux. If you'd like more detailed instructions, please refer to the [WINDOWS.md](https://github.com/hsa00000/Urocissa/blob/main/WINDOWS.md) file that I just added.
